// <auto-generated />
using System;
using FootBalLife.GameDB.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameDB.Migrations
{
    [DbContext(typeof(FootbalLifeDbContext))]
    partial class FootbalLifeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("FootBalLife.GameDB.Models.Agent", b =>
                {
                    b.Property<string>("PesonId")
                        .HasColumnType("TEXT");

                    b.HasKey("PesonId");

                    b.ToTable("Agent", (string)null);
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Coach", b =>
                {
                    b.Property<string>("PesonId")
                        .HasColumnType("TEXT");

                    b.HasKey("PesonId");

                    b.ToTable("Coach", (string)null);
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Contract", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SeasonFrom")
                        .IsRequired()
                        .HasColumnType("DATE");

                    b.Property<byte[]>("SeasonTo")
                        .IsRequired()
                        .HasColumnType("DATE");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("TeamId");

                    b.ToTable("Contract", (string)null);
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<byte[]>("Icon")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Director", b =>
                {
                    b.Property<string>("PesonId")
                        .HasColumnType("TEXT");

                    b.HasKey("PesonId");

                    b.ToTable("Director", (string)null);
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.League", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<long?>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CurrentRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("League", (string)null);
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Match", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<string>("Team1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Team2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Season")
                        .HasColumnType("TEXT");

                    b.Property<long>("Team1Goals")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Team2Goals")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WeekNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id", "Team1", "Team2", "Season");

                    b.HasIndex("Team1");

                    b.HasIndex("Team2");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.NationalResultTable", b =>
                {
                    b.Property<string>("Season")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Draws")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Loses")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MissedGoals")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ScoredGoals")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalPosition")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Season", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("NationalResultTable", (string)null);
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<byte[]>("Birthday")
                        .IsRequired()
                        .HasColumnType("DATE");

                    b.Property<long>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CurrentRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Icon")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CurrentRoleId");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Player", b =>
                {
                    b.Property<string>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Endurance")
                        .HasColumnType("INTEGER");

                    b.Property<long>("KickCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Passing")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Physics")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PositionId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Reflex")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Technique")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonId");

                    b.HasIndex("ContractId");

                    b.HasIndex("PositionId");

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<long>("Location")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Position", (string)null);
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<byte[]>("Icon")
                        .HasColumnType("BLOB");

                    b.Property<long?>("IsNpc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isNPC");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Scout", b =>
                {
                    b.Property<string>("PesonId")
                        .HasColumnType("TEXT");

                    b.HasKey("PesonId");

                    b.ToTable("Scout", (string)null);
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Team", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<long?>("AgentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CoachId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IsNationalTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.Property<long?>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SportsDirectorId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Strategy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Team", (string)null);
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Agent", b =>
                {
                    b.HasOne("FootBalLife.GameDB.Models.Person", "Peson")
                        .WithOne("Agent")
                        .HasForeignKey("FootBalLife.GameDB.Models.Agent", "PesonId")
                        .IsRequired();

                    b.Navigation("Peson");
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Coach", b =>
                {
                    b.HasOne("FootBalLife.GameDB.Models.Person", "Peson")
                        .WithOne("Coach")
                        .HasForeignKey("FootBalLife.GameDB.Models.Coach", "PesonId")
                        .IsRequired();

                    b.Navigation("Peson");
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Contract", b =>
                {
                    b.HasOne("FootBalLife.GameDB.Models.Person", "Person")
                        .WithMany("Contracts")
                        .HasForeignKey("PersonId")
                        .IsRequired();

                    b.HasOne("FootBalLife.GameDB.Models.Team", "Team")
                        .WithMany("Contracts")
                        .HasForeignKey("TeamId")
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Director", b =>
                {
                    b.HasOne("FootBalLife.GameDB.Models.Person", "Peson")
                        .WithOne("Director")
                        .HasForeignKey("FootBalLife.GameDB.Models.Director", "PesonId")
                        .IsRequired();

                    b.Navigation("Peson");
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.League", b =>
                {
                    b.HasOne("FootBalLife.GameDB.Models.Country", "Country")
                        .WithMany("Leagues")
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Match", b =>
                {
                    b.HasOne("FootBalLife.GameDB.Models.Team", "Team1Navigation")
                        .WithMany("MatchTeam1Navigations")
                        .HasForeignKey("Team1")
                        .IsRequired();

                    b.HasOne("FootBalLife.GameDB.Models.Team", "Team2Navigation")
                        .WithMany("MatchTeam2Navigations")
                        .HasForeignKey("Team2")
                        .IsRequired();

                    b.Navigation("Team1Navigation");

                    b.Navigation("Team2Navigation");
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.NationalResultTable", b =>
                {
                    b.HasOne("FootBalLife.GameDB.Models.Team", "Team")
                        .WithMany("NationalResultTables")
                        .HasForeignKey("TeamId")
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Person", b =>
                {
                    b.HasOne("FootBalLife.GameDB.Models.Country", "Country")
                        .WithMany("People")
                        .HasForeignKey("CountryId")
                        .IsRequired();

                    b.HasOne("FootBalLife.GameDB.Models.Role", "CurrentRole")
                        .WithMany("People")
                        .HasForeignKey("CurrentRoleId");

                    b.Navigation("Country");

                    b.Navigation("CurrentRole");
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Player", b =>
                {
                    b.HasOne("FootBalLife.GameDB.Models.Contract", "Contract")
                        .WithMany("Players")
                        .HasForeignKey("ContractId");

                    b.HasOne("FootBalLife.GameDB.Models.Person", "Person")
                        .WithOne("Player")
                        .HasForeignKey("FootBalLife.GameDB.Models.Player", "PersonId")
                        .IsRequired();

                    b.HasOne("FootBalLife.GameDB.Models.Position", "PositionNavigation")
                        .WithMany("Players")
                        .HasForeignKey("PositionId");

                    b.Navigation("Contract");

                    b.Navigation("Person");

                    b.Navigation("PositionNavigation");
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Scout", b =>
                {
                    b.HasOne("FootBalLife.GameDB.Models.Person", "Peson")
                        .WithOne("Scout")
                        .HasForeignKey("FootBalLife.GameDB.Models.Scout", "PesonId")
                        .IsRequired();

                    b.Navigation("Peson");
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Team", b =>
                {
                    b.HasOne("FootBalLife.GameDB.Models.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId");

                    b.Navigation("League");
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Contract", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Country", b =>
                {
                    b.Navigation("Leagues");

                    b.Navigation("People");
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.League", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Person", b =>
                {
                    b.Navigation("Agent");

                    b.Navigation("Coach");

                    b.Navigation("Contracts");

                    b.Navigation("Director");

                    b.Navigation("Player");

                    b.Navigation("Scout");
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Position", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Role", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("FootBalLife.GameDB.Models.Team", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("MatchTeam1Navigations");

                    b.Navigation("MatchTeam2Navigations");

                    b.Navigation("NationalResultTables");
                });
#pragma warning restore 612, 618
        }
    }
}
